language: php

sudo: false

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - COMPOSER_NO_INTERACTION="1"
    - COMPOSER_MEMORY_LIMIT="-1"

matrix:
  include:
    - php: 5.5
      env: COMPOSER_ARGS=""
    - php: 5.6
      env: COMPOSER_ARGS=""
    - php: 7.0
      env: COMPOSER_ARGS=""
    - php: 7.1
      env: COMPOSER_ARGS="" WITH_CS="true"
    - php: 7.2
      env: COMPOSER_ARGS=""

    - php: 5.5
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 5.6
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.0
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.1
      env: COMPOSER_ARGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_ARGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
  yarn: true

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - bash -c "composer update $COMPOSER_ARGS"

script:
    - vendor/bin/codecept run
    - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --stop-on-violation --using-cache=no --path-mode=intersection "${COMMIT_SCA_FILES[@]}"; fi
